# Build settings

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ----- Theme configuration -----
# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"
locale: "en-US"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# -----

title: Bilel DRIDI
subtitle: Software Engineer
name: Bilel DRIDI
email: bilel.dridi@shodo.io
description: >-
  Bilel DRIDI (Software Engineer / Tech Lead / Developer)
baseurl: ""
url: "https://bdridi.github.io"

# GitHub repository
github_username: bdridi
repository: "bdridi/bdridi.github.io"

# Personal information
author:
  name: "Bilel Dridi"
  avatar: "/assets/images/me.png"
  bio: Software Engineer at SHODO
  location: "Paris, France"
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/bdridi/"
    - label: "GitHub"
      icon: fab fa-fw fa-github
      url: "https://github.com/bdridi"
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: "https://twitter.com/the_bdridi"
twitter:
  username: the_bdridi
social:
  name: Bilel Dridi
  links:
    - "https://twitter.com/the_bdridi"
    - "https://www.linkedin.com/in/bdridi"
footer:
  links:
    - label: "GitHub"
      icon: fab fa-fw fa-github
      url: "https://github.com/bdridi"
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/bdridi"

#----


# Layout
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
atom_feed:
  hide: true